# Generated by Django 3.2.18 on 2023-02-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollnumber', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('dept', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('dob', models.CharField(max_length=20)),
                ('fatherName', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('bloodgrp', models.CharField(max_length=10)),
            ],
        ),
    ]
