# Generated by Django 3.2.18 on 2023-02-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CseSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcode', models.CharField(max_length=15)),
                ('subname', models.CharField(max_length=50)),
                ('semester', models.IntegerField()),
            ],
        ),
    ]
