# Generated by Django 3.2.18 on 2023-02-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_csesyllabus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fatherName',
            new_name='fathername',
        ),
        migrations.RemoveField(
            model_name='csesyllabus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='csesyllabus',
            name='subcode',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollnumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
