# Generated by Django 3.2.18 on 2023-02-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20230220_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='CseSemester1',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('HS8151', models.FloatField()),
                ('MA8151', models.FloatField()),
                ('PH8151', models.FloatField()),
                ('CY8151', models.FloatField()),
                ('GE8151', models.FloatField()),
                ('GE8152', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CseSemester2',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('HS8251', models.FloatField()),
                ('MA8251', models.FloatField()),
                ('PH8252', models.FloatField()),
                ('BE8255', models.FloatField()),
                ('GE8291', models.FloatField()),
                ('CS8251', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CseSemester3',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('MA8351', models.FloatField()),
                ('CS8351', models.FloatField()),
                ('CS8391', models.FloatField()),
                ('CS8392', models.FloatField()),
                ('EC8395', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CseSemester4',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('MA8402', models.FloatField()),
                ('CS8491', models.FloatField()),
                ('CS8492', models.FloatField()),
                ('CS8451', models.FloatField()),
                ('CS8493', models.FloatField()),
                ('CS8494', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CseSemester5',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('MA8551', models.FloatField()),
                ('CS8591', models.FloatField()),
                ('EC8691', models.FloatField()),
                ('CS8501', models.FloatField()),
                ('CS8592', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CseSemester6',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('CS8651', models.FloatField()),
                ('CS8691', models.FloatField()),
                ('CS8601', models.FloatField()),
                ('CS8602', models.FloatField()),
                ('CS8603', models.FloatField()),
                ('GE8075', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CseSemester7',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('MG8591', models.FloatField()),
                ('CS8792', models.FloatField()),
                ('CS8791', models.FloatField()),
                ('CS8092', models.FloatField()),
                ('CS8091', models.FloatField()),
                ('GE8077', models.FloatField()),
                ('GE8071', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CseSemester8',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('GE8076', models.FloatField()),
                ('CS8080', models.FloatField()),
            ],
        ),
    ]
