# Generated by Django 3.2.18 on 2023-02-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_csesemester1_csesemester2_csesemester3_csesemester4_csesemester5_csesemester6_csesemester7_csesemest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester1Internal1',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('HS8151', models.FloatField()),
                ('MA8151', models.FloatField()),
                ('PH8151', models.FloatField()),
                ('CY8151', models.FloatField()),
                ('GE8151', models.FloatField()),
                ('GE8152', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester1Internal2',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('HS8151', models.FloatField()),
                ('MA8151', models.FloatField()),
                ('PH8151', models.FloatField()),
                ('CY8151', models.FloatField()),
                ('GE8151', models.FloatField()),
                ('GE8152', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester1Model1',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('HS8151', models.FloatField()),
                ('MA8151', models.FloatField()),
                ('PH8151', models.FloatField()),
                ('CY8151', models.FloatField()),
                ('GE8151', models.FloatField()),
                ('GE8152', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester2Internal1',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('HS8251', models.FloatField()),
                ('MA8251', models.FloatField()),
                ('PH8252', models.FloatField()),
                ('BE8255', models.FloatField()),
                ('GE8291', models.FloatField()),
                ('CS8251', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester2Internal2',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('HS8251', models.FloatField()),
                ('MA8251', models.FloatField()),
                ('PH8252', models.FloatField()),
                ('BE8255', models.FloatField()),
                ('GE8291', models.FloatField()),
                ('CS8251', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester2Model1',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('HS8251', models.FloatField()),
                ('MA8251', models.FloatField()),
                ('PH8252', models.FloatField()),
                ('BE8255', models.FloatField()),
                ('GE8291', models.FloatField()),
                ('CS8251', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester3Internal1',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('MA8351', models.FloatField()),
                ('CS8351', models.FloatField()),
                ('CS8391', models.FloatField()),
                ('CS8392', models.FloatField()),
                ('EC8395', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester3Internal2',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('MA8351', models.FloatField()),
                ('CS8351', models.FloatField()),
                ('CS8391', models.FloatField()),
                ('CS8392', models.FloatField()),
                ('EC8395', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester3Model1',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('MA8351', models.FloatField()),
                ('CS8351', models.FloatField()),
                ('CS8391', models.FloatField()),
                ('CS8392', models.FloatField()),
                ('EC8395', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester4Internal1',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('MA8402', models.FloatField()),
                ('CS8491', models.FloatField()),
                ('CS8492', models.FloatField()),
                ('CS8451', models.FloatField()),
                ('CS8493', models.FloatField()),
                ('CS8494', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester4Internal2',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('MA8402', models.FloatField()),
                ('CS8491', models.FloatField()),
                ('CS8492', models.FloatField()),
                ('CS8451', models.FloatField()),
                ('CS8493', models.FloatField()),
                ('CS8494', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester4Model1',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('MA8402', models.FloatField()),
                ('CS8491', models.FloatField()),
                ('CS8492', models.FloatField()),
                ('CS8451', models.FloatField()),
                ('CS8493', models.FloatField()),
                ('CS8494', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester5Internal1',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('MA8551', models.FloatField()),
                ('CS8591', models.FloatField()),
                ('EC8691', models.FloatField()),
                ('CS8501', models.FloatField()),
                ('CS8592', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester5Internal2',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('MA8551', models.FloatField()),
                ('CS8591', models.FloatField()),
                ('EC8691', models.FloatField()),
                ('CS8501', models.FloatField()),
                ('CS8592', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester5Model1',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('MA8551', models.FloatField()),
                ('CS8591', models.FloatField()),
                ('EC8691', models.FloatField()),
                ('CS8501', models.FloatField()),
                ('CS8592', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester6Internal1',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('CS8651', models.FloatField()),
                ('CS8691', models.FloatField()),
                ('CS8601', models.FloatField()),
                ('CS8602', models.FloatField()),
                ('CS8603', models.FloatField()),
                ('GE8075', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester6Internal2',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('CS8651', models.FloatField()),
                ('CS8691', models.FloatField()),
                ('CS8601', models.FloatField()),
                ('CS8602', models.FloatField()),
                ('CS8603', models.FloatField()),
                ('GE8075', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester6Model1',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('CS8651', models.FloatField()),
                ('CS8691', models.FloatField()),
                ('CS8601', models.FloatField()),
                ('CS8602', models.FloatField()),
                ('CS8603', models.FloatField()),
                ('GE8075', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester7Internal1',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('MG8591', models.FloatField()),
                ('CS8792', models.FloatField()),
                ('CS8791', models.FloatField()),
                ('CS8092', models.FloatField()),
                ('CS8091', models.FloatField()),
                ('GE8077', models.FloatField()),
                ('GE8071', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester7Internal2',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('MG8591', models.FloatField()),
                ('CS8792', models.FloatField()),
                ('CS8791', models.FloatField()),
                ('CS8092', models.FloatField()),
                ('CS8091', models.FloatField()),
                ('GE8077', models.FloatField()),
                ('GE8071', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester7Model1',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('MG8591', models.FloatField()),
                ('CS8792', models.FloatField()),
                ('CS8791', models.FloatField()),
                ('CS8092', models.FloatField()),
                ('CS8091', models.FloatField()),
                ('GE8077', models.FloatField()),
                ('GE8071', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester8Internal1',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('GE8076', models.FloatField()),
                ('CS8080', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester8Internal2',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('GE8076', models.FloatField()),
                ('CS8080', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester8Model1',
            fields=[
                ('rollnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('GE8076', models.FloatField()),
                ('CS8080', models.FloatField()),
            ],
        ),
    ]
